[package]
name = "bench"
version = "0.1.0"
edition = "2024"

[dependencies]
leet = { path = ".." }

[lib]
bench = false

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "reduce_steps"
harness = false

[[bench]]
name = "robot_sim_874"
harness = false

[[bench]]
name = "pivot_array_2161"
harness = false

[[bench]]
name = "max_total_value_3689"
harness = false